In [131]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [132]:
df = pd.read_csv('Heart_Disease.csv')

In [133]:
df.head()

male  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39        4.0              0         0.0     0.0                0   
1     0   46        2.0              0         0.0     0.0                0   
2     1   48        1.0              1        20.0     0.0                0   
3     0   61        3.0              1        30.0     0.0                0   
4     0   46        3.0              1        23.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0   
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0   
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0   
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0   
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0   

   TenYearCHD  
0           0  
1           0  
2           0  
3           1  
4           0

In [134]:
df.isnull().sum()

male                 0
age                  0
education          105
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

In [135]:
df.drop(['education','cigsPerDay','prevalentStroke','glucose'],axis=1,inplace=True)

In [136]:
df.isnull().sum()

male              0
age               0
currentSmoker     0
BPMeds           53
prevalentHyp      0
diabetes          0
totChol          50
sysBP             0
diaBP             0
BMI              19
heartRate         1
TenYearCHD        0
dtype: int64

In [137]:
df['BPMeds'] = df['BPMeds'].fillna(df['BPMeds'].median())
df['totChol'] = df['totChol'].fillna(df['totChol'].median())
df['BMI'] = df['BMI'].fillna(df['BMI'].median())
df['heartRate'] = df['heartRate'].fillna(df['heartRate'].median())

In [138]:
df.isnull().sum()

male             0
age              0
currentSmoker    0
BPMeds           0
prevalentHyp     0
diabetes         0
totChol          0
sysBP            0
diaBP            0
BMI              0
heartRate        0
TenYearCHD       0
dtype: int64

In [139]:
X = df.drop('TenYearCHD',axis=1)
y=df['TenYearCHD']

In [140]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=40)

In [141]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [142]:
from sklearn.ensemble import RandomForestClassifier

my_model = RandomForestClassifier(n_estimators=50,criterion='entropy',random_state=60)
result = my_model.fit(X_train,y_train)

In [143]:
prediction = result.predict(X_test)
prediction

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [144]:
from sklearn.metrics import accuracy_score

accuracy_score(prediction,y_test)*100

85.25943396226415

In [145]:
from sklearn.metrics import f1_score

f1_score(prediction,y_test)

0.1258741258741259

In [146]:
df.loc[df['TenYearCHD']==1]

male  age  currentSmoker  BPMeds  prevalentHyp  diabetes  totChol  \
3        0   61              1     0.0             1         0    225.0   
6        0   63              0     0.0             0         0    205.0   
15       0   38              1     0.0             1         0    221.0   
17       0   46              1     0.0             0         0    291.0   
25       1   47              1     0.0             0         0    294.0   
...    ...  ...            ...     ...           ...       ...      ...   
4221     1   50              0     0.0             0         0    260.0   
4223     1   56              0     1.0             1         0    287.0   
4226     1   58              0     0.0             0         0    233.0   
4232     1   68              0     0.0             1         0    176.0   
4233     1   50              1     0.0             1         0    313.0   

      sysBP  diaBP    BMI  heartRate  TenYearCHD  
3     150.0   95.0  28.58       65.0           1  
6     138.0   71.0  33.11       60.0           1  
15    140.0   90.0  21.35       95.0           1  
17    112.0   78.0  23.38       80.0           1  
25    102.0   68.0  24.18       62.0           1  
...     ...    ...    ...        ...         ...  
4221  119.0   74.0  21.85       80.0           1  
4223  149.0   98.0  21.68       90.0           1  
4226  125.5   84.0  26.05       67.0           1  
4232  168.0   97.0  23.14       60.0           1  
4233  179.0   92.0  25.97       66.0           1  

[644 rows x 12 columns]

In [147]:
pred_new = result.predict([[1,39,0,0.0,0,0,195.0,106.0,70.0,26.97,80.0]])
pred_new

array([1], dtype=int64)

In [157]:
new_pred = result.predict([[1,75,0,53.0,1,0,254.0,160.0,71.0,32.10,58.0]])
new_pred

array([0], dtype=int64)

In [155]:
pred3 = result.predict([[1,50,0,0.0,0,0,260.0,119.0,74.0,21.85,80.0]])
pred3

array([1], dtype=int64)

In [161]:
pred4 = result.predict([[1,58,0,0.0,1,0,187.0,141.0,81.0,24.96,80.0]])
pred4

array([0], dtype=int64)